name: securdialog
version: 0.0.1
summary: Secure collection of health data
description: Collecting health data, particularly related to diabetes..

confinement: strict
base: core18
grade: stable

slots:
  dbus-rattle: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: com.togaware.securedialog # adjust accordingly to your app name and
    
apps:
  securedialog:
    command: securedialog
    extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build
    plugs:
    - network
    slots:
      - dbus-securedialog
parts:
  securedialog:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
